### ISSUE TITLE
Error getting scrobble data of '<username>': Failure

### ISSUE THREAD

**Issue by EmSixTeen** [SHOEGAZEssb/Last.fm-Scrubbler-WPF#97] opened 2020-04-16 10:00 UTC
Hey, getting this error when I try and retrieve my scrobbles using the CSV Downloader or Milestone Checker.

Seems to occur at different points of the process every time.

Last.fm-Scrubbler-WPF: 1.22.0.0
OS: Win 10 Pro (10.0.18363).

```[16/04/2020 11:19:40]: Getting user info of 'EmSixTeen'...
[16/04/2020 11:19:40]: Getting scrobble data of 'EmSixTeen'... (1 / 145) pages
[16/04/2020 11:19:47]: Getting scrobble data of 'EmSixTeen'... (2 / 145) pages
[16/04/2020 11:19:50]: Error getting scrobble data of 'EmSixTeen': Failure
[16/04/2020 11:36:39]: Getting user info of 'EmSixTeen'...
[16/04/2020 11:36:40]: Getting scrobble data of 'EmSixTeen'... (1 / 145) pages
[16/04/2020 11:36:46]: Getting scrobble data of 'EmSixTeen'... (2 / 145) pages
[16/04/2020 11:36:54]: Getting scrobble data of 'EmSixTeen'... (3 / 145) pages
[16/04/2020 11:37:00]: Getting scrobble data of 'EmSixTeen'... (4 / 145) pages
[16/04/2020 11:37:06]: Getting scrobble data of 'EmSixTeen'... (5 / 145) pages
[16/04/2020 11:37:09]: Error getting scrobble data of 'EmSixTeen': Failure
[16/04/2020 11:49:30]: Getting user info of 'emsixteen'...
[16/04/2020 11:49:31]: Getting scrobble data of 'emsixteen'... (1 / 145) pages
[16/04/2020 11:49:43]: Getting scrobble data of 'emsixteen'... (2 / 145) pages
[16/04/2020 11:49:50]: Getting scrobble data of 'emsixteen'... (3 / 145) pages
[16/04/2020 11:49:57]: Getting scrobble data of 'emsixteen'... (4 / 145) pages
[16/04/2020 11:50:02]: Getting scrobble data of 'emsixteen'... (5 / 145) pages
[16/04/2020 11:50:08]: Getting scrobble data of 'emsixteen'... (6 / 145) pages
[16/04/2020 11:50:14]: Getting scrobble data of 'emsixteen'... (7 / 145) pages
[16/04/2020 11:50:20]: Getting scrobble data of 'emsixteen'... (8 / 145) pages
[16/04/2020 11:50:26]: Getting scrobble data of 'emsixteen'... (9 / 145) pages
[16/04/2020 11:50:35]: Getting scrobble data of 'emsixteen'... (10 / 145) pages
[16/04/2020 11:50:44]: Getting scrobble data of 'emsixteen'... (11 / 145) pages
[16/04/2020 11:50:51]: Getting scrobble data of 'emsixteen'... (12 / 145) pages
[16/04/2020 11:50:57]: Getting scrobble data of 'emsixteen'... (13 / 145) pages
[16/04/2020 11:51:02]: Getting scrobble data of 'emsixteen'... (14 / 145) pages
[16/04/2020 11:51:09]: Getting scrobble data of 'emsixteen'... (15 / 145) pages
[16/04/2020 11:51:18]: Getting scrobble data of 'emsixteen'... (16 / 145) pages
[16/04/2020 11:51:26]: Getting scrobble data of 'emsixteen'... (17 / 145) pages
[16/04/2020 11:51:31]: Getting scrobble data of 'emsixteen'... (18 / 145) pages
[16/04/2020 11:51:36]: Getting scrobble data of 'emsixteen'... (19 / 145) pages
[16/04/2020 11:51:46]: Getting scrobble data of 'emsixteen'... (20 / 145) pages
[16/04/2020 11:51:51]: Getting scrobble data of 'emsixteen'... (21 / 145) pages
[16/04/2020 11:51:56]: Getting scrobble data of 'emsixteen'... (22 / 145) pages
[16/04/2020 11:52:01]: Getting scrobble data of 'emsixteen'... (23 / 145) pages
[16/04/2020 11:52:05]: Getting scrobble data of 'emsixteen'... (24 / 145) pages
[16/04/2020 11:52:10]: Getting scrobble data of 'emsixteen'... (25 / 145) pages
[16/04/2020 11:52:15]: Getting scrobble data of 'emsixteen'... (26 / 145) pages
[16/04/2020 11:52:24]: Getting scrobble data of 'emsixteen'... (27 / 145) pages
[16/04/2020 11:52:33]: Getting scrobble data of 'emsixteen'... (28 / 145) pages
[16/04/2020 11:52:38]: Getting scrobble data of 'emsixteen'... (29 / 145) pages
[16/04/2020 11:52:44]: Getting scrobble data of 'emsixteen'... (30 / 145) pages
[16/04/2020 11:52:52]: Getting scrobble data of 'emsixteen'... (31 / 145) pages
[16/04/2020 11:53:02]: Getting scrobble data of 'emsixteen'... (32 / 145) pages
[16/04/2020 11:53:08]: Getting scrobble data of 'emsixteen'... (33 / 145) pages
[16/04/2020 11:53:18]: Getting scrobble data of 'emsixteen'... (34 / 145) pages
[16/04/2020 11:53:22]: Getting scrobble data of 'emsixteen'... (35 / 145) pages
[16/04/2020 11:53:28]: Getting scrobble data of 'emsixteen'... (36 / 145) pages
[16/04/2020 11:53:32]: Error getting scrobble data of 'emsixteen': Failure
[16/04/2020 11:56:31]: Waiting to scrobble...
[16/04/2020 11:56:41]: Fetching top artists of 'emsixteen'...
[16/04/2020 11:56:42]: Successfully fetched top artists of 'emsixteen'
[16/04/2020 11:57:10]: Fetching page 1 / 145
[16/04/2020 11:57:15]: Fetching page 2 / 145
[16/04/2020 11:57:21]: Fetching page 3 / 145
[16/04/2020 11:57:27]: Fetching page 4 / 145
[16/04/2020 11:57:35]: Fetching page 5 / 145
[16/04/2020 11:57:42]: Fetching page 6 / 145
[16/04/2020 11:57:51]: Fetching page 7 / 145
[16/04/2020 11:58:02]: Fetching page 8 / 145
[16/04/2020 11:58:07]: Fetching page 9 / 145
[16/04/2020 11:58:17]: Fetching page 10 / 145
[16/04/2020 11:58:23]: Fetching page 11 / 145
[16/04/2020 11:58:29]: Fetching page 12 / 145
[16/04/2020 11:58:34]: Fetching page 13 / 145
[16/04/2020 11:58:39]: Fetching page 14 / 145
[16/04/2020 11:58:46]: Fetching page 15 / 145
[16/04/2020 11:58:51]: Fetching page 16 / 145
[16/04/2020 11:58:58]: Fetching page 17 / 145
[16/04/2020 11:59:05]: Fetching page 18 / 145
[16/04/2020 11:59:12]: Fetching page 19 / 145
[16/04/2020 11:59:20]: Fetching page 20 / 145
[16/04/2020 11:59:25]: Fetching page 21 / 145
[16/04/2020 11:59:30]: Fetching page 22 / 145
[16/04/2020 11:59:35]: Fetching page 23 / 145
[16/04/2020 11:59:40]: Fetching page 24 / 145
[16/04/2020 11:59:44]: Fetching page 25 / 145
[16/04/2020 11:59:48]: Fetching page 26 / 145
[16/04/2020 11:59:53]: Fetching page 27 / 145
[16/04/2020 12:00:00]: Error while fetching scrobble data: Failure

**Comment by coczero** [comment] 2020-04-16 11:53
Hi this is a known issue currently.
You can use this in the meantime: http://benjaminbenben.com/lastfm-to-csv/

**Comment by SHOEGAZEssb** [comment] 2024-03-29 08:55
Duplicate of https://github.com/SHOEGAZEssb/Last.fm-Scrubbler-WPF/issues/86

**Closed** 2024-03-29 08:56 UTC
